Blockly.Msg.WEBDUINO_G3_NEW = "细悬浮微粒传感器，接收脚位";
Blockly.Msg.WEBDUINO_G3_TX = "传送脚位";
Blockly.Msg.WEBDUINO_G3_GET = "侦测细悬浮微粒，每";
Blockly.Msg.WEBDUINO_G3_READ = "侦测细悬浮微粒";
Blockly.Msg.WEBDUINO_G3_GET_TIME = "毫秒 ( 1/1000 秒 ) 撷取一次";
Blockly.Msg.WEBDUINO_G3_GET_DO = "执行";
Blockly.Msg.WEBDUINO_G3_GET_NOW = "所测得目前的";
Blockly.Msg.WEBDUINO_G3_GET_PM25 = "PM2.5";
Blockly.Msg.WEBDUINO_G3_GET_PM10 = "PM10";